apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: storage-pvc
    namespace: production
spec:
    resources:
        requests:
            storage: 20Gi
    accessModes:
        - ReadWriteOnce
