apiVersion: v1
kind: Service
metadata:
    name: redis
    namespace: production
    labels:
        app: rp-appeals
        type: redis
        env: prod
spec:
    type: ClusterIP
    ports:
        - port: 6379
          protocol: TCP
          targetPort: entry
    selector:
        app: rp-appeals
        type: redis
        env: prod

