apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: redis-pvc
    namespace: staging
spec:
    resources:
        requests:
            storage: 1Gi
    accessModes:
        - ReadWriteOnce
