export enum MyFaxStatus {
    FAX_STATUS_INIT = 0,
    FAX_STATUS_CONFIRM = 1,
    FAX_STATUS_NO_ANSWER = 2,
    FAX_STATUS_BUSY = 3,
    FAX_STATUS_CONNECT = 4,
    FAX_STATUS_WRONG_NUMBER = 6,
    FAX_STATUS_FAIL = 7,
    FAX_STATUS_SENT = 9,
    FAX_STATUS_DELETE = 10,
}
