apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: production
    labels:
        app: rp-appeals
        type: frontend
        env: prod
spec:
    type: ClusterIP
    ports:
        - port: 3000
          name: entry
          protocol: TCP
          targetPort: 3000
    selector:
        app: rp-appeals
        type: frontend
        env: prod

