apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: production
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    replicas: 1
    selector:
        matchLabels:
            app: rp-appeals
            type: frontend
            env: prod
    template:
        metadata:
            labels:
                app: rp-appeals
                type: frontend
                env: prod
        spec:
            containers:
                - name: frontend
                  image: eu.gcr.io/appeals-265314/frontend:stable
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                        name: entry
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 20
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 20
                      periodSeconds: 10
                  env:
                      - name: PORT
                        value: '3000'
                  envFrom:
                      - secretRef:
                            name: frontend
