apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: metabase-storage-pvc
    namespace: production
spec:
    resources:
        requests:
            storage: 10Gi
    accessModes:
        - ReadWriteOnce
