/**
 * All API
 * TODO: Add Description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class GenerateTicketDefenseRequest {
    'ticketId': string;
    'customParagraphs': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'ticketId',
            baseName: 'ticketId',
            type: 'string',
        },
        {
            name: 'customParagraphs',
            baseName: 'customParagraphs',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return GenerateTicketDefenseRequest.attributeTypeMap;
    }
}
