/**
 * All API
 * TODO: Add Description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineObject1 {
    'violationId': string;
    'direction': string;
    'ticketId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'violationId',
            baseName: 'violationId',
            type: 'string',
        },
        {
            name: 'direction',
            baseName: 'direction',
            type: 'string',
        },
        {
            name: 'ticketId',
            baseName: 'ticketId',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return InlineObject1.attributeTypeMap;
    }
}
