/**
 * All API
 * TODO: Add Description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineObject {
    'firstName': string;
    'lastName': string;
    'mobile': string;
    'ticketSystem': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'firstName',
            baseName: 'firstName',
            type: 'string',
        },
        {
            name: 'lastName',
            baseName: 'lastName',
            type: 'string',
        },
        {
            name: 'mobile',
            baseName: 'mobile',
            type: 'string',
        },
        {
            name: 'ticketSystem',
            baseName: 'ticketSystem',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineObject.attributeTypeMap;
    }
}
