/**
 * All API
 * TODO: Add Description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UploadTicketDocumentRequest {
    'ticketId': number;
    'ticketDocumentBase64': string;
    'ticketDocumentMimeType': string;
    'documentDescription': string;
    'documentTypeCode': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'ticketId',
            baseName: 'ticketId',
            type: 'number',
        },
        {
            name: 'ticketDocumentBase64',
            baseName: 'ticketDocumentBase64',
            type: 'string',
        },
        {
            name: 'ticketDocumentMimeType',
            baseName: 'ticketDocumentMimeType',
            type: 'string',
        },
        {
            name: 'documentDescription',
            baseName: 'documentDescription',
            type: 'string',
        },
        {
            name: 'documentTypeCode',
            baseName: 'documentTypeCode',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return UploadTicketDocumentRequest.attributeTypeMap;
    }
}
